name: Release

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install @yaakapp/cli
        run: npm install -g @yaakapp/cli

      - name: Install Dependencies
        run: npm install

      - name: Build Plugins
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm test
